dependencies:
  - python=3.12.11
  - pip
  - affine
  - cfgrib
  - dask
  - dask-geopandas
  - dask-image
  - fiona
  - geopandas
  - netcdf4
  - numba
  - numpy
  - pandas
  - pygeos
  - pyogrio
  - pyproj
  - rasterio
  - rioxarray
  - scipy
  - shapely
  - xarray
  - ipywidgets
  - ipyleaflet
  - localtileserver
  - ipyfilechooser
  - voila
  - osmnx
  - py3dep
  - pystac-client
  - stackstac
  - scikit-learn
  - planetary-computer
  - jupyter-server-proxy
  - pip:
      - raster-tools
