name: rstools
channels:
  - conda-forge
  - defaults
dependencies:
  - ipyleflet
  - ipywidgets
  - localtileserver
  - ipyfilechooser
  - affine
  - build
  - dask
  - dask-geopandas
  - dask-image
  - fiona
  - geopandas
  - numba
  - numpy
  - pandas
  - pygeos
  - pyogrio
  - pyproj
  - rasterio
  - rioxarray
  - scipy
  - shapely>=2.0
  - twine
  - xarray
  - pip:
      - raster-tools
