name: rstools
channels:
  - conda-forge
  - defaults
dependencies:
  - python=10
  - pip
  - ipyleaflet
  - ipywidgets
  - localtileserver=0.7.2
  - ipyfilechooser
  - voila
  - affine
  - dask
  - dask-geopandas
  - dask-image
  - fiona
  - geopandas
  - numba
  - numpy
  - pandas
  - pygeos
  - pyogrio
  - pyproj
  - rasterio
  - rioxarray
  - scipy
  - shapely>=2.0
  - xarray
  - osmnx
  - py3dep
  - pystac-client
  - stackstac
  - scikit-learn
  - planetary-computer
  - jupyter-server-proxy
  - pip:
      - raster-tools
