dependencies:
  - python=3.10
  - affine
  - cfgrib
  - dask<=2024.2.1
  - dask-geopandas
  - dask-image
  - fiona
  - geopandas
  - netcdf4
  - numba
  - numpy
  - pandas
  - pygeos
  - pyogrio
  - pyproj
  - rasterio
  - rioxarray
  - scipy
  - shapely>=2.0
  - xarray
  - ipyleaflet
  - localtileserver=0.7.2
  - ipyfilechooser
  - voila
  - osmnx
  - py3dep
  - pystac-client
  - stackstac
  - scikit-learn
  - planetary-computer
  - jupyter-server-proxy
  - pip:
      - raster-tools
